<?PHP
// vim: ts=4:sw=4:fdc=4:nospell
/**
  * Script that includes individual Ext 3.x files for debugging purposes
  * 
  * Usage: Include this script in the page header *after* resources and adapter
  * Example:
  *  <link rel="stylesheet" type="text/css" href="ext/resources/css/ext-all.css">
  *  <script type="text/javascript" src="ext/adapter/ext/ext-base.js"></script>
  *  <?require_once("ext.php");?>
  *
  * @author     Ing. Jozef Sakalos
  * @copyright  (c) 2009, by Ing. Jozef Sakalos
  * @date       7. September 2009
  * @version    1.0
  * @revision   $Id$
  *
  * @license ext.php is licensed under the terms of the Open Source
  * LGPL 3.0 license. Commercial use is permitted to the extent that the 
  * code/component(s) do NOT become part of another Open Source or Commercially
  * licensed development library or toolkit without explicit permission.
  * 
  * License details: http://www.gnu.org/licenses/lgpl.html
  */

// set extPath relative to the path of your index file
$extPath = "ext-3.1+";  // edit for my site

// path to jsb2 file
$jsbFile = "$extPath/ext.jsb2";

// javascript include template
$template = "  <script type=\"text/javascript\" src=\"{file}\"></script>\n";

// read the jsb2 file
$h = fopen($jsbFile, "r");
$buff = fread($h, filesize($jsbFile));
fclose($h);

// the content needs a bit of conditioning before we can json_decode it
$buff = preg_replace("/'/", '"', $buff);
$buff = preg_replace("/([\ \t]*)(\w+):(.*)/", "\$1\"\$2\":\$3", $buff);

// decode the file
$jsbRaw = json_decode($buff, true);

// create associative array from the indexed array
$jsb = array();
foreach($jsbRaw["pkgs"] as $pkg) {
    $jsb[$pkg["file"]] = $pkg;
}

// loop through entries and output script tags
echo "\n  <!-- ExtJS 3.x includes generated by "
    . basename(__FILE__) . " -->\n"
;
foreach($jsb["ext-all.js"]["pkgDeps"] as $pkg) {
    foreach($jsb[$pkg]["fileIncludes"] as $incl) {
        $file = "$extPath/${incl['path']}${incl['text']}";
        echo preg_replace("/\{file\}/", $file, $template);
    }
}
echo "  <!-- ExtJS 3.x includes generated by " 
    . basename(__FILE__) . " End -->\n\n"
;

// eof
?>


